[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/series"
  to = "/series/"
  status = 301

[[redirects]]
  from = "/tools"
  to = "/tools/"
  status = 301
